# Generated by Django 5.0.6 on 2024-12-02 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('iddispositivo', models.IntegerField(db_column='idDispositivo', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'dispositivo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('idpelicula', models.AutoField(db_column='idPelicula', primary_key=True, serialize=False)),
                ('nombrepelicula', models.CharField(blank=True, db_column='nombrePelicula', max_length=60, null=True)),
                ('tipopelicula', models.CharField(blank=True, db_column='tipoPelicula', max_length=30, null=True)),
                ('fechavista', models.DateField(blank=True, db_column='fechaVista', null=True)),
                ('fechaterminada', models.DateField(blank=True, db_column='fechaTerminada', null=True)),
            ],
            options={
                'db_table': 'pelicula',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('idserie', models.IntegerField(db_column='idSerie', primary_key=True, serialize=False)),
                ('nombreserie', models.CharField(blank=True, db_column='nombreSerie', max_length=60, null=True)),
                ('tiposerie', models.CharField(blank=True, db_column='tipoSerie', max_length=30, null=True)),
                ('fechavista', models.DateField(blank=True, db_column='fechaVista', null=True)),
                ('fechaterminada', models.DateField(blank=True, db_column='fechaTerminada', null=True)),
            ],
            options={
                'db_table': 'serie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subscripcion',
            fields=[
                ('idsubscripcion', models.IntegerField(db_column='idSubscripcion', primary_key=True, serialize=False)),
                ('fechainicio', models.DateField(blank=True, db_column='fechaInicio', null=True)),
                ('fechatermino', models.DateField(blank=True, db_column='fechaTermino', null=True)),
            ],
            options={
                'db_table': 'subscripcion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.IntegerField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('idemail', models.CharField(db_column='idEmail', max_length=78)),
                ('nombre', models.CharField(max_length=50)),
                ('fechanacimiento', models.DateField(db_column='fechaNacimiento')),
                ('ciudad', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Valoracionpelicula',
            fields=[
                ('idpelicula', models.OneToOneField(db_column='idPelicula', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='appNetflix.pelicula')),
                ('valoracionpelicula', models.DecimalField(db_column='valoracionPelicula', decimal_places=0, max_digits=10)),
            ],
            options={
                'db_table': 'valoracionpelicula',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Valoracionserie',
            fields=[
                ('idserie', models.OneToOneField(db_column='idSerie', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='appNetflix.serie')),
                ('valoracionserie', models.DecimalField(db_column='valoracionSerie', decimal_places=0, max_digits=10)),
            ],
            options={
                'db_table': 'valoracionserie',
                'managed': False,
            },
        ),
    ]
